name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Build & Deploy
      env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
      run: echo "$PRIVATE_KEY" > private_key && chmod 600 private_key && cat private_key
    - name: scp
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ec2-43-201-209-69.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key_path: ./private_key
        port: 22
        source: "README.md"
        target: /home/ec2-user/app
    - name: ssh 
      run: ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-43-201-209-69.ap-northeast-2.compute.amazonaws.com '
            cd /home/ec2-user/app &&
            ls README.md
            '

